source("../SurvSimu.R")
args = commandArgs(trailingOnly=TRUE)
i=as.numeric(args[1])
filename=paste("SimuData_s2A_",i,".csv",sep="")
getSimulated(filename,group_size=1,group_num=8000,lambda=0.0000008,rho=2.8,effective_group=16,sample_size=500,within_group_cor=0.3)
